In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn import feature_extraction, linear_model, model_selection, preprocessing
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

In [4]:
fake = pd.read_csv("D:\\VARSHITHA\\fake news detection\\Fake.csv", dtype=str)
true = pd.read_csv("D:\\VARSHITHA\\fake news detection\\True.csv", dtype=str)

In [5]:
fake.shape

(23481, 4)

In [6]:
true.shape

(21417, 4)

In [7]:
# Add flag to track fake and real
fake['target'] = 'fake'
true['target'] = 'true'

In [8]:
# Concatenate dataframes
data = pd.concat([fake, true]).reset_index(drop = True)
data.shape

(44898, 5)

In [9]:
# Shuffle the data
from sklearn.utils import shuffle
data = shuffle(data)
data = data.reset_index(drop=True)

In [10]:
# Check the data
data.head()

,title,text,subject,date,target
0,TRUMP’S UN AMBASSADOR Nikki Haley Warns UN Mem...,New US Ambassador Nikki Haley strutted into th...,politics,"Jan 27, 2017",fake
1,Argentina Congress passes pension reform after...,BUENOS AIRES (Reuters) - Argentina s Congress ...,worldnews,"December 19, 2017",true
2,"Iraq PM to visit Turkey on Wednesday, discuss ...",ANKARA (Reuters) - Iraqi Prime Minister Haider...,worldnews,"October 23, 2017",true
3,Howard Dean ROASTS Trump Over Debate Sniffles...,"In the first half of the debate, Donald Trump ...",News,"September 27, 2016",fake
4,SYRIAN MUSLIM IMMIGRANT HAIRDRESSER SLITS Fema...,She wanted him to assimilate. She gave him a g...,politics,"Jul 17, 2017",fake

In [11]:
# Removing the date (we won't use it for the analysis)
data.drop(["date"],axis=1,inplace=True)
data.head()

,title,text,subject,target
0,TRUMP’S UN AMBASSADOR Nikki Haley Warns UN Mem...,New US Ambassador Nikki Haley strutted into th...,politics,fake
1,Argentina Congress passes pension reform after...,BUENOS AIRES (Reuters) - Argentina s Congress ...,worldnews,true
2,"Iraq PM to visit Turkey on Wednesday, discuss ...",ANKARA (Reuters) - Iraqi Prime Minister Haider...,worldnews,true
3,Howard Dean ROASTS Trump Over Debate Sniffles...,"In the first half of the debate, Donald Trump ...",News,fake
4,SYRIAN MUSLIM IMMIGRANT HAIRDRESSER SLITS Fema...,She wanted him to assimilate. She gave him a g...,politics,fake

In [12]:
# Removing the title (we will only use the text)
data.drop(["title"],axis=1,inplace=True)
data.head()

                                                text    subject target
0  New US Ambassador Nikki Haley strutted into th...   politics   fake
1  BUENOS AIRES (Reuters) - Argentina s Congress ...  worldnews   true
2  ANKARA (Reuters) - Iraqi Prime Minister Haider...  worldnews   true
3  In the first half of the debate, Donald Trump ...       News   fake
4  She wanted him to assimilate. She gave him a g...   politics   fake

In [13]:
# Convert to lowercase

data['text'] = data['text'].apply(lambda x: x.lower())
data.head()

                                                text    subject target
0  new us ambassador nikki haley strutted into th...   politics   fake
1  buenos aires (reuters) - argentina s congress ...  worldnews   true
2  ankara (reuters) - iraqi prime minister haider...  worldnews   true
3  in the first half of the debate, donald trump ...       News   fake
4  she wanted him to assimilate. she gave him a g...   politics   fake

In [19]:
# Remove punctuation

import string

def punctuation_removal(text):
    all_list = [char for char in text if char not in string.punctuation]
    clean_str = ''.join(all_list)
    return clean_str

data['text'] = data['text'].apply(punctuation_removal)

In [20]:
# Check
data.head()

                                                text    subject target
0  new us ambassador nikki haley strutted un frid...   politics   fake
1  buenos aires reuters argentina congress passed...  worldnews   true
2  ankara reuters iraqi prime minister haider ala...  worldnews   true
3  first half debate donald trump seemed bogged d...       News   fake
4  wanted assimilate gave good job trusted offere...   politics   fake

In [21]:
# Removing stopwords
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
stop = stopwords.words('english')

data['text'] = data['text'].apply(lambda x: ' '.join([word for word in x.split() if word not in (stop)]))

[nltk_data] Downloading package stopwords to C:\Users\UMESH B
[nltk_data]     K\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [22]:
data.head()

                                                text    subject target
0  new us ambassador nikki haley strutted un frid...   politics   fake
1  buenos aires reuters argentina congress passed...  worldnews   true
2  ankara reuters iraqi prime minister haider ala...  worldnews   true
3  first half debate donald trump seemed bogged d...       News   fake
4  wanted assimilate gave good job trusted offere...   politics   fake

In [23]:
# Save the cleaned dataset to CSV
data.to_csv("D:\\VARSHITHA\\fake news detection\\Cleaned_FakeNews.csv", index=False)

print("✅ Cleaned dataset saved as 'Cleaned_FakeNews.csv'")

✅ Cleaned dataset saved as 'Cleaned_FakeNews.csv'